name: ptgp
channels:
    - conda-forge
dependencies:
    - python>=3.11
    - pymc>=5.28.4
    - jax
    - jaxlib
    - optax
    - scipy
    - libblas=*=*mkl
    - mkl-service
    - pytest
    - gpjax
    - ipykernel
    - ipywidgets
    - ipympl
    - matplotlib
    - seaborn
    - pandas
    - scikit-learn
    - arviz
    - pip
    - pip:
        - pymc-extras>=0.2.3
        - git+https://github.com/pymc-devs/pytensor@assumption-system
